//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeroEngine.DefaultResources", typeof(DefaultResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Needs to be redone.
        /// </summary>
        internal static string binding {
            get {
                return ResourceManager.GetString("binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //To add a resource (yes modders, over here). Use this syntax:
        /////GRASS_NORMAL:Tiles/tile-00
        /////Newlines are new files.
        /////TYPE is not too important for modders. (Texture, Sound, Music)
        /////NOT USED AT THIS MOMENT IN THE ENGINE.
        /// </summary>
        internal static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //To add a resource (yes modders, over here). Use this syntax:
        /////GRASS_NORMAL:Tiles/tile-00
        /////Newlines are new files.
        /////TYPE is not too important for modders. (Texture, Sound, Music)
        ///TYPE:Font
        ///AmmoCount:gui/font/ammo_count
        ///MenuItem:gui/font/menu_item
        ///SmallText:gui/font/small_text
        ///StatusMessage:gui/font/status_message
        ///TitleText:gui/font/TitleText
        ///.
        /// </summary>
        internal static string fonts {
            get {
                return ResourceManager.GetString("fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //To add a resource (yes modders, over here). Use this syntax:
        /////GRASS_NORMAL:Tiles/tile-00
        /////Newlines are new files.
        /////TYPE is not too important for modders. (Texture, Sound, Music)
        ///TYPE:Music
        ///TRACK1:sound\music\examplemusic01
        ///TRACK2:sound\music\examplemusic02
        ///TRACK3:sound\music\examplemusic03.
        /// </summary>
        internal static string music {
            get {
                return ResourceManager.GetString("music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Video]
        ///Width = 1024
        ///Height = 768
        ///Fullscreen = false.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //To add a resource (yes modders, over here). Use this syntax:
        /////GRASS_NORMAL:Tiles/tile-00
        /////Newlines are new files.
        /////TYPE is not too important for modders. (Texture, Sound, Music)
        ///TYPE:Sound.
        /// </summary>
        internal static string sounds {
            get {
                return ResourceManager.GetString("sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        /////To add a resource (yes modders, over here). Use this syntax:
        /////GRASS_NORMAL:Tiles/tile-00
        /////Newlines are new files.
        /////For the tiles you will be needing to keep the Names the same as the TileLookup Database.
        /////TYPE is not too important for modders. (Texture, Sound, Music)
        ///
        ///
        /////Configure
        ///TYPE:Texture
        ///
        /////Our Tiles
        ///BLANK:Tiles/tile-00
        ///WATER:Tiles/water
        ///SAND:Tiles/sand
        ///ROCK:Tiles/rock
        ///GRASS:Tiles/grass
        ///
        /////Hud
        ///TORCH:hud\torch
        ///MINIMAP:hud\minimap
        ///HPBAR:hud\stat_bars\armour
        ///ARMOUR:hud\stat_bars\hpbar
        ///
        /////Player
        ///P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string texture {
            get {
                return ResourceManager.GetString("texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //This file is a large one, but nessacery. Formatting as follows:
        /////{
        /////ID=
        /////Type=
        /////CanWalkOn=TRUE/FALSE
        /////Size=WidthxHeight
        /////Frames=2
        /////Speed=100 (in ms)
        /////}
        ///{
        ///ID=0
        ///Type=BLANK
        ///CanWalkOn=FALSE
        ///Size=128x128
        ///Frames=1
        ///Speed=0
        ///}
        ///{
        ///ID=1
        ///Type=WATER
        ///CanWalkOn=FALSE
        ///Size=128x128
        ///Frames=2
        ///Speed=300
        ///}
        ///{
        ///ID=2
        ///Type=SAND
        ///CanWalkOn=TRUE
        ///Size=128x128
        ///Frames=1
        ///Speed=0
        ///}
        ///{
        ///ID=3
        ///Type=GRASS
        ///CanWalkOn=TRUE
        ///Size=128x128
        ///Frames=1
        ///Speed=0
        ///}
        ///{
        ///ID=4
        ///Type=ROCK
        ///CanWalkOn=TRUE
        ///Size=128x128
        ///Frames=1
        ///Speed=0
        ///}.
        /// </summary>
        internal static string tiles {
            get {
                return ResourceManager.GetString("tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //To add a resource (yes modders, over here). Use this syntax:
        /////GRASS_NORMAL:Tiles/tile-00
        /////Newlines are new files.
        /////TYPE is not too important for modders. (Texture, Sound, Music)
        ///TYPE:Music
        ///INTROVIDEO:videos\intro.
        /// </summary>
        internal static string videos {
            get {
                return ResourceManager.GetString("videos", resourceCulture);
            }
        }
    }
}
